"""Generate auditable Vivado batch scripts from validated, typed inputs."""

from __future__ import annotations

import re

from ...common.errors import BadRequest
from ...common.tcl import TCL_DECODE_PROC, b64encode_utf8

_RUN_NAME = re.compile(r"[A-Za-z_][A-Za-z0-9_.-]*\Z")
_TARGETS = {"synth", "impl", "bitstream", "flow"}
_FLOW_SUFFIXES = {".v", ".vh", ".sv", ".svh", ".vhd", ".vhdl"}


def generate_project_script(
    *,
    project: str,
    target: str,
    run: str | None,
    jobs: int,
    reset: bool,
    strategy: str | None,
    report_dir: str | None = None,
) -> str:
    if target not in _TARGETS:
        raise BadRequest(
            f"unknown build target {target!r}; expected {sorted(_TARGETS)}"
        )
    if not 1 <= jobs <= 64:
        raise BadRequest("jobs must be between 1 and 64")

    default_run = "synth_1" if target == "synth" else "impl_1"
    run = run or default_run
    if not _RUN_NAME.fullmatch(run):
        raise BadRequest(f"invalid Vivado run name: {run!r}")

    to_step = {
        "synth": None,
        "impl": "route_design",
        "bitstream": "write_bitstream",
        "flow": "write_bitstream",
    }[target]
    lines = [
        "# Generated by vivado-mcp. This file is safe to run independently.",
        *TCL_DECODE_PROC,
        f"set vmcp_project [vmcp_decode {{{b64encode_utf8(project)}}}]",
        f"set vmcp_run [vmcp_decode {{{b64encode_utf8(run)}}}]",
        "open_project $vmcp_project",
    ]
    if strategy:
        lines += [
            f"set vmcp_strategy [vmcp_decode {{{b64encode_utf8(strategy)}}}]",
            "set_property strategy $vmcp_strategy [get_runs $vmcp_run]",
        ]
    if reset:
        lines.append("reset_run $vmcp_run")
    launch = f"launch_runs $vmcp_run -jobs {jobs}"
    if to_step:
        launch += f" -to_step {to_step}"
    lines += [
        launch,
        "wait_on_run $vmcp_run",
        "set vmcp_status [get_property STATUS [get_runs $vmcp_run]]",
        'puts "VMCP run status: $vmcp_status"',
        "if {![string match {*Complete*} $vmcp_status]} {",
        '    error "Vivado run $vmcp_run ended with status: $vmcp_status"',
        "}",
    ]
    if report_dir:
        lines += _report_lines(report_dir, open_run=True)
    lines += [
        "close_project",
        "exit 0",
        "",
    ]
    return "\n".join(lines)


def generate_flow_script(
    *,
    sources: list[str],
    xdc: list[str],
    part: str,
    top: str,
    target: str,
    report_dir: str | None = None,
) -> str:
    if target not in {"synth", "impl", "bitstream"}:
        raise BadRequest("flow target must be synth, impl, or bitstream")
    if not sources:
        raise BadRequest("flow_run needs at least one HDL source")
    lines = [
        "# Generated by vivado-mcp. Non-project flow; safe to run independently.",
        *TCL_DECODE_PROC,
        f"set vmcp_part [vmcp_decode {{{b64encode_utf8(part)}}}]",
        f"set vmcp_top [vmcp_decode {{{b64encode_utf8(top)}}}]",
    ]
    for index, source in enumerate(sources):
        suffix = source.lower().rsplit(".", 1)
        extension = f".{suffix[-1]}" if len(suffix) == 2 else ""
        if extension not in _FLOW_SUFFIXES:
            raise BadRequest(f"unsupported HDL source type: {source!r}")
        variable = f"vmcp_source_{index}"
        lines.append(f"set {variable} [vmcp_decode {{{b64encode_utf8(source)}}}]")
        if extension in {".sv", ".svh"}:
            lines.append(f"read_verilog -sv ${variable}")
        elif extension in {".vhd", ".vhdl"}:
            lines.append(f"read_vhdl ${variable}")
        else:
            lines.append(f"read_verilog ${variable}")
    for index, constraint in enumerate(xdc):
        variable = f"vmcp_xdc_{index}"
        lines += [
            f"set {variable} [vmcp_decode {{{b64encode_utf8(constraint)}}}]",
            f"read_xdc ${variable}",
        ]
    lines += [
        "synth_design -top $vmcp_top -part $vmcp_part",
        "write_checkpoint -force post_synth.dcp",
    ]
    if target in {"impl", "bitstream"}:
        lines += [
            "opt_design",
            "place_design",
            "phys_opt_design",
            "route_design",
            "write_checkpoint -force post_route.dcp",
        ]
    if target == "bitstream":
        lines.append("write_bitstream -force ${vmcp_top}.bit")
    if report_dir:
        lines += _report_lines(report_dir, open_run=False)
    lines += ["exit 0", ""]
    return "\n".join(lines)


def _report_lines(report_dir: str, *, open_run: bool) -> list[str]:
    """Generate a best-effort normalized report bundle without failing a build."""
    lines = [
        f"set vmcp_report_dir [vmcp_decode {{{b64encode_utf8(report_dir)}}}]",
        "file mkdir $vmcp_report_dir",
        "proc vmcp_try_report {name command} {",
        "    if {[catch {uplevel 1 $command} vmcp_error]} {",
        r'        puts "WARNING: \[VMCP Report 1-1\] $name failed: $vmcp_error"',
        "    }",
        "}",
    ]
    if open_run:
        lines.append("open_run $vmcp_run")
    reports = (
        ("utilization", "report_utilization", "utilization.rpt"),
        (
            "utilization_hierarchical",
            "report_utilization -hierarchical",
            "utilization_hierarchical.rpt",
        ),
        ("timing_summary", "report_timing_summary -max_paths 10", "timing_summary.rpt"),
        ("clocks", "report_clocks", "clocks.rpt"),
        ("drc", "report_drc", "drc.rpt"),
        ("methodology", "report_methodology", "methodology.rpt"),
        ("cdc", "report_cdc", "cdc.rpt"),
        ("power", "report_power", "power.rpt"),
    )
    for name, command, filename in reports:
        lines.append(
            "vmcp_try_report "
            f"{{{name}}} [list {command} -file [file join $vmcp_report_dir {{{filename}}}]]"
        )
    return lines
